### ISSUE TITLE
Version is not supported in this release

### ISSUE THREAD

**Issue by RunSi** [CiscoDevNet/NX-SDK#2]
I have created an RPM for a python script using the docker image v1.7.5
When I try and instantiate the service after activating I get the following message
```
sbx-n9kv-ao(config)# nxsdk service-name FibrePorts.py
Error: Service FibrePorts.py Version is not supported on this release, check supported versions
```
This application works with a previous RPM I created using docker image v1.

Also tried example application
```
sbx-n9kv-ao(config)# nxsdk service-name pbwMonitor
Error: Service pbwMonitor Version is not supported on this release, check supported versions
```

I am testing this on a N9000v
```
Nexus 9000v is a demo version of the Nexus Operating System

Software
  BIOS: version 
  NXOS: version 9.2(1)
  BIOS compile time:  
  NXOS image file is: bootflash:///nxos.9.2.1.bin
  NXOS compile time:  7/17/2018 16:00:00 [07/18/2018 00:21:19]
```
Which NXOS versions are supported

**Comment by sattysri** [comment]
Can you please attach 
  - the output of "show nxsdk internal service" command from your switch?
  - the rpm package name for your application?

**Comment by sattysri** [comment]
Closing this issue. Please reopen if you are still encountering this issue.
