### ISSUE TITLE
Docker image v1

### ISSUE THREAD

**Issue by RunSi** [CiscoDevNet/NX-SDK#3]
Docker image v1 does not have the scripts directory and thus no rpm_gen.py
To overcome I initiated a GIT pull from the NX-SDK directory.
When I now run rpm_gen.py it creates the RPM but with V1.7.5 tag not V1

**Comment by sattysri** [comment]
1) Docker image v1 does not have the scripts directory and thus no rpm_gen.py?
- Did you pull v1 using the following:
    git clone -b v1.0.0 https://github.com/CiscoDevNet/NX-SDK.git

With the above command, it has the scripts dir. 
Can you please attach the steps to reproduce the issue?

 LICENSE  Makefile  README.md  description.md  doc  examples  include  rpm  scripts  stubs
root@5171c186710d:/NX-SDK-v1/NX-SDK# cd scripts/
root@5171c186710d:/NX-SDK-v1/NX-SDK/scripts# ls
rpm_gen.py  template.spec

2) To overcome I initiated a GIT pull from the NX-SDK directory.
When I now run rpm_gen.py it creates the RPM but with V1.7.5 tag not V1

Use the -r <sdk_version> option while building the RPM to specify the NX-SDK version for your RPM package.

Ex)
root@5171c186710d:/NX-SDK/scripts# python rpm_gen.py -h
usage: rpm_gen.py [-h] [-s SOURCE] [-u | -t TARGET] [-d DESCRIPTION]
                  [-v VERSION] [-r SDK_VERSION]
                  name

This script generates RPM packages for custom applications built using NX-
SDK.Please export the path for NX-SDK as environment variable NXSDK_ROOT and
ENXOS-SDK as environment variable ENXOS_SDK_ROOT before calling the script.If
not found, the script assumes NX-SDK to be present at the following location
/NX-SDK and ENXOS-SDK to be present at /enxos-sdk

positional arguments:
  name                  Name of the application binary or the file name in
                        case of python

optional arguments:
  -h, --help            show this help message and exit
  -s SOURCE, --source SOURCE
                        Path of the folder where application source files are
                        present (default: /NX-SDK/examples)
  -u, --use_source_as_target
                        If the source file is the same as the executable
                        (default: False)
  -t TARGET, --target TARGET
                        Path where the application binary or the python file
                        is present (default: /NX-SDK/bin)
  -d DESCRIPTION, --description DESCRIPTION
                        Application Description (default: RPM package for
                        custom application)
  -v VERSION, --version VERSION
                        Application Version (default: 1.0)
  -r SDK_VERSION, --sdk_version SDK_VERSION
                        NX-SDK Release Version (default: 1.7.5)

root@5171c186710d:/NX-SDK/scripts# python rpm_gen.py pbwMonitor -s ../examples/python -u -r 1.0.0

**Comment by RunSi** [comment]
Hi thanks for the assistance.  I should have seen the tags in the repo, apologies.

It works now by doing the following
```
root@f92f59f4290b:/NX-SDK# git fetch --all --tags

root@f92f59f4290b:/NX-SDK# git checkout v1.0.0 
```

Did not need to use the -r <version>, option, the rpm created is suffixed with 1.0.0
